### ISSUE TITLE
Потрібний фікс для дизайну (добавляння відео).

### ISSUE THREAD

**Issue by QusDev** [NexTubeOrg/NexTube_Frontend#15]
1. Пофіксити скрол в оверлеї добавляння відео (оверлей блочить скрол і на малих екранах не видно всього контенту).

![image](https://github.com/NexTubeOrg/NexTube_Frontend/assets/92417930/f629404a-d6c4-4fd6-86ea-1cc510709471)

2. Добавити можливість вибирати прев'ю відео [дизайн].
3. Добавити можливість вибирати саме відео [дизайн].

**Comment by Devlonic** [comment]
fixed

**Comment by Devlonic** [comment]
fixed.
